import { Product } from "@/types";
import { Categories } from "./constants";

export const filterOptions = [
  { key: "price_low_to_high", label: "Price: Low to High" },
  { key: "price_high_to_low", label: "Price: High to Low" },
  { key: "new_arrivals", label: "New Arrivals" },
] as const;

const images = [
  "/images/productDetail/p1.png",
  "/images/productDetail/p2.png",
  "/images/productDetail/p3.png",
  "/images/productDetail/p4.png",
];

const colors = ["#E5E5E5", "#E7B250", "#094745"];

// export const products: Product[] = [
//   {
//     id: 1,
//     code: "MW001",
//     name: "Belisenna Steel Watch – Silver",
//     description: "Men’s stainless steel watch with silver finish.",
//     price: 14199,
//     oldPrice: 15399,
//     // quantity: 0,
//     category: Categories.MENWATCHES,
//     stockQuantity: 40,
//     colorOptions: colors,
//     coverImageUrl: "/images/watches/p2.png",
//     images,
//   },
//   {
//     id: 2,
//     code: "MW002",
//     name: "Retro 70's Watch – Sage Green",
//     description: "Retro-inspired men’s watch with green dial.",
//     price: 9899,
//     oldPrice: 10399,
//     // quantity: 0,
//     category: Categories.MENWATCHES,
//     stockQuantity: 35,
//     colorOptions: colors,
//     coverImageUrl: "/images/watches/p17.png",
//     images,
//   },
//   {
//     id: 3,
//     code: "MW003",
//     name: "Triomphe Mesh Watch – Black Gold",
//     description: "Luxury mesh strap watch with black and gold tones.",
//     price: 11999,
//     oldPrice: 13499,
//     // quantity: 0,
//     category: Categories.MENWATCHES,
//     stockQuantity: 28,
//     colorOptions: colors,
//     coverImageUrl: "/images/watches/p20.png",
//     images,
//   },
//   {
//     id: 4,
//     code: "MW004",
//     name: "La Tétragone Watch – Black Gold",
//     description: "Square dial premium men’s watch.",
//     price: 14199,
//     oldPrice: 15399,
//     // quantity: 0,
//     category: Categories.MENWATCHES,
//     stockQuantity: 22,
//     colorOptions: colors,
//     coverImageUrl: "/images/watches/p18.png",
//     images,
//   },

//   {
//     id: 5,
//     code: "WW001",
//     name: "Gracieuse Petite Watch – Gold",
//     description: "Slim women’s watch with gold finish.",
//     price: 2499,
//     oldPrice: 2999,
//     // quantity: 0,
//     category: Categories.WOMENWATCHES,
//     stockQuantity: 50,
//     colorOptions: colors,
//     coverImageUrl: "/images/watches/p10.png",
//     images,
//   },
//   {
//     id: 6,
//     code: "WW002",
//     name: "Minuit Mesh Watch – White Dial",
//     description: "Minimal women’s mesh watch with white dial.",
//     price: 9899,
//     oldPrice: 10399,
//     // quantity: 0,
//     category: Categories.WOMENWATCHES,
//     stockQuantity: 32,
//     colorOptions: colors,
//     coverImageUrl: "/images/watches/p8.png",
//     images,
//   },
//   {
//     id: 7,
//     code: "WW003",
//     name: "Gracieuse Mini Watch – Full Gold",
//     description: "Compact women’s watch with full gold color.",
//     price: 8999,
//     oldPrice: 9999,
//     // quantity: 0,
//     category: Categories.WOMENWATCHES,
//     stockQuantity: 26,
//     colorOptions: colors,
//     coverImageUrl: "/images/watches/p12.png",
//     images,
//   },
//   {
//     id: 8,
//     code: "WW004",
//     name: "Fluette Leather Watch – Black",
//     description: "Elegant leather strap watch for women.",
//     price: 7999,
//     oldPrice: 8999,
//     // quantity: 0,
//     category: Categories.WOMENWATCHES,
//     stockQuantity: 29,
//     colorOptions: colors,
//     coverImageUrl: "/images/watches/p5.png",
//     images,
//   },

//   {
//     id: 9,
//     code: "JW001",
//     name: "Lillypearlie Earrings",
//     description: "Elegant handcrafted pearl earrings.",
//     price: 800,
//     oldPrice: 1999,
//     // quantity: 0,
//     category: Categories.JEWELLERY,
//     stockQuantity: 100,
//     colorOptions: colors,
//     coverImageUrl: "/images/watches/p1.png",
//     images,
//   },
//   // {
//   //   id: 10,
//   //   code: "JW002",
//   //   name: "Gold Finish Pendant Necklace",
//   //   description: "Minimal gold-plated pendant necklace.",
//   //   price: 1499,
//   //   oldPrice: 1999,
//     // quantity: 0,
//   //   category: Categories.JEWELLERY,
//   //   stockQuantity: 75,
//   //   colorOptions: colors,
//   //   coverImageUrl: "/images/jewellery/j1.png",
//   //   images,
//   // },
//   // {
//   //   id: 11,
//   //   code: "JW003",
//   //   name: "Crystal Stud Earrings",
//   //   description: "Premium crystal stud earrings.",
//   //   price: 999,
//   //   oldPrice: 1499,
//   //   quantity: 0,
//   //   category: Categories.JEWELLERY,
//   //   stockQuantity: 120,
//   //   colorOptions: colors,
//   //   coverImageUrl: "/images/jewellery/j2.png",
//   //   images,
//   // },
//   // {
//   //   id: 12,
//   //   code: "JW004",
//   //   name: "Charm Bracelet – Gold",
//   //   description: "Stylish charm bracelet with gold finish.",
//   //   price: 1799,
//   //   oldPrice: 2499,
//   //   quantity: 0,
//   //   category: Categories.JEWELLERY,
//   //   stockQuantity: 60,
//   //   colorOptions: colors,
//   //   coverImageUrl: "/images/jewellery/j3.png",
//   //   images,
//   // },
//   // {
//   //   id: 13,
//   //   code: "PR001",
//   //   name: "Leather Hand Purse – Black",
//   //   description: "Premium leather purse with multiple compartments.",
//   //   price: 3499,
//   //   oldPrice: 4499,
//   //   quantity: 0,
//   //   category: Categories.PURSES,
//   //   stockQuantity: 20,
//   //   colorOptions: colors,
//   //   coverImageUrl: "/images/purses/p1.png",
//   //   images,
//   // },
//   // {
//   //   id: 14,
//   //   code: "PR002",
//   //   name: "Elegant Shoulder Purse – Beige",
//   //   description: "Stylish shoulder purse for everyday use.",
//   //   price: 2999,
//   //   oldPrice: 3999,
//   //   quantity: 0,
//   //   category: Categories.PURSES,
//   //   stockQuantity: 18,
//   //   colorOptions: colors,
//   //   coverImageUrl: "/images/purses/p2.png",
//   //   images,
//   // },
//   // {
//   //   id: 15,
//   //   code: "PR003",
//   //   name: "Compact Crossbody Purse – Brown",
//   //   description: "Lightweight crossbody purse with zip closure.",
//   //   price: 2599,
//   //   oldPrice: 3299,
//   //   quantity: 0,
//   //   category: Categories.PURSES,
//   //   stockQuantity: 24,
//   //   colorOptions: colors,
//   //   coverImageUrl: "/images/purses/p3.png",
//   //   images,
//   // },
//   // {
//   //   id: 16,
//   //   code: "PR004",
//   //   name: "Luxury Tote Bag – Tan",
//   //   description: "Spacious tote bag for work and travel.",
//   //   price: 4999,
//   //   oldPrice: 5999,
//   //   quantity: 0,
//   //   category: Categories.PURSES,
//   //   stockQuantity: 15,
//   //   colorOptions: colors,
//   //   coverImageUrl: "/images/purses/p4.png",
//   //   images,
//   // },
//   {
//     id: 17,
//     code: "MW005",
//     name: "Minuit Multifunction Watch – Leather",
//     description: "Multifunction men’s watch with leather strap.",
//     price: 10999,
//     oldPrice: 12499,
//     quantity: 0,
//     category: Categories.MENWATCHES,
//     stockQuantity: 27,
//     colorOptions: colors,
//     coverImageUrl: "/images/watches/p9.png",
//     images,
//   },
//   {
//     id: 18,
//     code: "WW005",
//     name: "Gracieuse Petite Watch – Mauve Pink",
//     description: "Elegant women’s watch with mauve pink dial.",
//     price: 2499,
//     oldPrice: 2999,
//     quantity: 0,
//     category: Categories.WOMENWATCHES,
//     stockQuantity: 31,
//     colorOptions: colors,
//     coverImageUrl: "/images/watches/p21.png",
//     images,
//   },
//   // {
//   //   id: 19,
//   //   code: "JW005",
//   //   name: "Minimal Ring Set – Gold",
//   //   description: "Set of minimal gold-finish rings.",
//   //   price: 1299,
//   //   oldPrice: 1799,
//   //   quantity: 0,
//   //   category: Categories.JEWELLERY,
//   //   stockQuantity: 90,
//   //   colorOptions: colors,
//   //   coverImageUrl: "/images/jewellery/j4.png",
//   //   images,
//   // },
//   // {
//   //   id: 20,
//   //   code: "PR005",
//   //   name: "Mini Evening Purse – Black",
//   //   description: "Compact purse perfect for evening outings.",
//   //   price: 2199,
//   //   oldPrice: 2799,
//   //   quantity: 0,
//   //   category: Categories.PURSES,
//   //   stockQuantity: 19,
//   //   colorOptions: colors,
//   //   coverImageUrl: "/images/purses/p5.png",
//   //   images,
//   // },
// ];
